leftnav:
- identifier: efc59ed4-4600-5de8-829d-f25391248098
  name: Syllabus
  url: /pages/syllabus
  weight: 10
- identifier: 1e48ef4b-fbb2-af7a-55e8-dad47b28a54b
  name: Calendar
  url: /pages/calendar
  weight: 20
- identifier: e0cad4f9-2117-929b-ddcf-c653b315379c
  name: Readings
  url: /pages/readings
  weight: 30
- identifier: 47936637-1c57-05e1-7af2-bfadff19c163
  name: Projects
  url: /pages/projects
  weight: 40
- identifier: b3c6b3e0-51d2-5533-55fb-a1fef08ed31a
  name: Image Gallery
  url: /pages/image-gallery
  weight: 50
